---
- name: restart activemq
  service:
    name: activemq
    state: restarted
    enabled: yes

- name: restart message-consumer
  service:
    name: message-consumer
    state: restarted
    enabled: yes

- name: restart gunicorn
  service:
    name: gunicorn
    state: restarted
    enabled: yes

- name: restart celery
  service:
    name: celery
    state: restarted
    enabled: yes

- name: restart celerybeat
  service:
    name: celerybeat
    state: restarted
    enabled: yes